POST http://127.0.0.1:5000/capture HTTP/1.1
Content-Type: application/json

{
    "action":"start",
    "thing": {
        "id":"XY00-9",
        "tag":"XY00"
    }
}

###
POST http://127.0.0.1:5000/capture HTTP/1.1
Content-Type: application/json

{
    "action":"stop"
}

###
GET http://127.0.0.1:5000/docs HTTP/1.1
Content-Type: application/json

###
GET http://127.0.0.1:5000/ping HTTP/1.1
Content-Type: application/json
